- name: Install containerd
  apt:
    name: containerd
    state: present
    update_cache: yes

- name: Ensure containerd config directory exists
  file:
    path: /etc/containerd
    state: directory

- name: Generate default containerd config
  command: containerd config default
  register: containerd_config
  changed_when: false

- name: Write containerd config
  copy:
    dest: /etc/containerd/config.toml
    content: "{{ containerd_config.stdout }}"
  notify: Restart containerd

- name: Enable SystemdCgroup
  replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'
  notify: Restart containerd

- name: Ensure containerd is running
  service:
    name: containerd
    state: started
    enabled: true