- name: Update apt cache
  apt:
    update_cache: yes

- name: Upgrade packages
  apt:
    upgrade: dist

- name: Install base packages
  apt:
    name:
      - curl
      - vim
      - git
      - htop
      - net-tools
    state: present